Rework tests
filecoin-station/voyager-api pull request #22
Opened 2024-04-24 07:53 UTC by bajtos

Following up on the discussion in https://github.com/filecoin-station/voyager-api/pull/15#discussion_r1561206334, I am proposing to rework the publisher test suite as follows:

- In the unit tests, use the real database and mock the web3.storage and IE Contract clients. This allows us to run the tests locally with no interaction with production services and verify how the system handles various edge cases (e.g. contract invocation taking too long).
- I left the integration tests mostly as-is; the only change is to clean up the code to use the newly introduced test helpers.

I don't see value in asserting on individual SQL queries and the parameters - these are implementation details that can change. Tests should verify the observed behaviour, not the implementation. Instead of comparing SQL query arguments, I check that we have correctly deleted the published measurements - that's what matters.

I also started to structure the tests to make it easier to copy and paste some of the files from Voyager to Spark.

The diff is quite large and a lot of the changes are not related to parallelising the publishing process in #15. I am happy to split this PR into several smaller ones and/or make the changes to the `main` branch so that you can rebase #15 to use the new test architecture. Let me know what do you prefer!

2024-04-24 07:55 UTC, bajtos commented on voyager-publish/test/unit.test.js
Most of the test code in this file can be shared between Spark and Voyager. I propose moving it to `voyager-publish/test/platform-unit.test.js` so that it's easier to copy and paste the changes from one repo to another.

WDYT?

2024-04-24 08:22 UTC, juliangruber commented
> I don't see value in asserting on individual SQL queries and the parameters - these are implementation details that can change. Tests should verify the observed behaviour, not the implementation. Instead of comparing SQL query arguments, I check that we have correctly deleted the published measurements - that's what matters.

+100

2024-04-24 09:08 UTC, juliangruber requested changes
Great start Miro! TYSM!

2024-04-24 12:49 UTC, bajtos commented on voyager-publish/test/platform-test-helpers.js
> What about `meridian-test-helpers`? Not important though

That name works too 👍🏻 

I am using platform-test-helpers to be consistent with what we recommended @PatrickNercessian to use in his work in spark-evalute and spark-stats.

2024-04-30 08:57 UTC, juliangruber approved these changes
👏 tysm!

2024-04-30 14:39 UTC, merged