feat: include process id in publish-batch logs
filecoin-station/voyager-api pull request #38
Opened 2024-05-07 14:38 UTC by bajtos

Make it easier to understand interleaved log messages from multiple children processes running concurrently.

2024-05-07 17:43 UTC, juliangruber requested changes
good idea!

2024-05-07 17:43 UTC, juliangruber commented on voyager-publish/bin/publish-batch.js
> +  }
```suggestion
  args.unshift(`[worker:${process.pid}]`)
```

I think that should create the same result

2024-05-07 17:43 UTC, juliangruber commented on voyager-publish/bin/publish-batch.js
> +  error (...args) { console.log(...addPidToConsoleArgs(...args)) }
```suggestion
  error (...args) { console.error(...addPidToConsoleArgs(...args)) }
```

2024-05-07 17:44 UTC, juliangruber commented on voyager-publish/bin/publish-batch.js
> +  }
no scratch that it doesn't, because of fprintf formatting. But I think I have a different idea

2024-05-07 17:45 UTC, juliangruber requested changes

2024-05-07 17:46 UTC, juliangruber commented on voyager-publish/bin/publish-batch.js
> +  }
see next review

2024-05-09 11:14 UTC, bajtos commented on voyager-publish/bin/publish-batch.js
> +  return args
The problem with your suggestion is that `console.log` applies colours to arguments while `util.format` does not.

<img width="421" alt="Screenshot 2024-05-09 at 13 13 35" src="https://github.com/filecoin-station/voyager-api/assets/1140553/ec2fb08d-0ebb-4899-9b05-b9b708532266">

2024-05-10 14:38 UTC, juliangruber approved these changes

2024-05-13 08:37 UTC, merged